"""Parameter-efficient fine-tuning primitives."""

from typing import TYPE_CHECKING, Any

from about_llm.finetuning.data import (
    SFT_DATA_CONTRACT_VERSION,
    ChatMessage,
    DataSplit,
    DuplicateGroup,
    FunctionToolCall,
    FunctionToolDefinition,
    MessageRole,
    SFTDataAuditReport,
    SFTRecord,
    SFTTrainingBindingReport,
    audit_sft_records,
    load_sft_records,
    validate_training_records,
    validate_training_subset,
)
from about_llm.finetuning.governance import (
    SFT_GOVERNANCE_AUDIT_VERSION,
    SFT_GOVERNANCE_POLICY_VERSION,
    SFT_SENSITIVE_CANDIDATE_DETECTOR_VERSION,
    CandidateDisposition,
    CandidateException,
    GovernanceOutcome,
    GovernancePurpose,
    SensitiveCandidateFinding,
    SensitiveTextSurface,
    SFTGovernanceAuditReport,
    SFTGovernancePolicy,
    SourceDecision,
    SourceDecisionFinding,
    SourceRule,
    audit_sft_governance,
    load_sft_governance_policy,
    parse_utc_timestamp,
    scan_sensitive_text_surfaces,
)
from about_llm.finetuning.gradient_accumulation import (
    CategoricalMicrobatch,
    CategoricalTokenRecord,
    DDPGradientAccumulationAnalysis,
    DDPTokenMeanAnalysis,
    GradientAccumulationAnalysis,
    MicrobatchGradientContribution,
    analyze_default_ddp_gradient_accumulation,
    analyze_default_ddp_token_mean,
    analyze_masked_token_gradient_accumulation,
)
from about_llm.finetuning.memory import (
    QLoRAMemoryEstimate,
    estimate_qlora_memory,
    oom_degradation_order,
)
from about_llm.finetuning.minhash_lsh import (
    MINHASH_LSH_VERSION,
    ExactLSHCandidateComparison,
    MinHashLSHCandidatePair,
    MinHashLSHCandidateReport,
    MinHashLSHConfig,
    MinHashLSHRecallAudit,
    audit_minhash_lsh_recall,
    exact_recheck_lsh_candidates,
    generate_minhash_lsh_candidates,
    lsh_candidate_probability,
    minhash_signature,
)
from about_llm.finetuning.near_duplicate import (
    SFT_NEAR_DUPLICATE_AUDIT_VERSION,
    NearDuplicateFinding,
    NearDuplicateProfile,
    NearDuplicateView,
    SFTNearDuplicateAuditReport,
    audit_sft_near_duplicates,
    character_ngrams,
    normalize_near_duplicate_text,
    shingle_jaccard,
)
from about_llm.finetuning.peft_export import (
    PEFT_EXPORT_MANIFEST_FILENAME,
    PEFT_EXPORT_MANIFEST_VERSION,
    PEFTExportIdentity,
    PEFTExportLimits,
    PEFTExportVerification,
    verify_peft_export_directory,
    write_peft_export_manifest_new,
)
from about_llm.finetuning.policy_gradient import (
    CategoricalPolicyGradientReport,
    GroupRelativeAdvantageReport,
    categorical_policy_gradient,
    group_relative_advantages,
    variance_minimizing_score_baseline,
)
from about_llm.finetuning.ppo import (
    GeneralizedAdvantageEstimate,
    PPOClippedSurrogateReport,
    generalized_advantage_estimation,
    masked_mean,
    ppo_clipped_surrogate,
)
from about_llm.finetuning.preference import (
    bradley_terry_loss,
    dpo_logit,
    dpo_loss,
    sequence_log_probability,
)
from about_llm.finetuning.preference_data import (
    PREFERENCE_DATA_CONTRACT_VERSION,
    PreferenceDataAuditReport,
    PreferenceDuplicateGroup,
    PreferenceLabel,
    PreferenceRecord,
    PreferenceStrength,
    PreferenceTrainingBindingReport,
    audit_preference_records,
    load_preference_records,
    preference_audit_manifest_fingerprint,
    validate_dpo_training_records,
    validate_dpo_training_subset,
)
from about_llm.finetuning.preference_evaluation import (
    PREFERENCE_EVALUATION_VERSION,
    PREFERENCE_JUDGMENT_AUDIT_VERSION,
    PREFERENCE_JUDGMENT_CONTRACT_VERSION,
    PreferenceEvaluationSummary,
    PreferenceJudgment,
    PreferenceJudgmentAuditReport,
    audit_preference_judgments,
    load_preference_judgments,
    summarize_preference_judgments,
)
from about_llm.finetuning.preference_governance import (
    PREFERENCE_GOVERNANCE_AUDIT_VERSION,
    PREFERENCE_SENSITIVE_CANDIDATE_DETECTOR_VERSION,
    PreferenceGovernanceAuditReport,
    audit_preference_governance,
)
from about_llm.finetuning.preference_near_duplicate import (
    PREFERENCE_NEAR_DUPLICATE_AUDIT_VERSION,
    PreferenceNearDuplicateAuditReport,
    PreferenceNearDuplicateFinding,
    PreferenceNearDuplicateView,
    audit_preference_near_duplicates,
)
from about_llm.finetuning.preference_readiness import (
    PREFERENCE_TRAINING_READINESS_VERSION,
    PreferenceTrainingReadinessReport,
    load_preference_training_readiness,
    validate_preference_training_readiness,
)
from about_llm.finetuning.preference_template import (
    PREFERENCE_TOKENIZATION_AUDIT_VERSION,
    PreferenceTemplateRenderer,
    PreferenceTokenizationAuditReport,
    PreferenceTokenizationSample,
    audit_preference_tokenization,
)
from about_llm.finetuning.readiness import (
    SFT_TRAINING_READINESS_VERSION,
    SFTTrainingReadinessReport,
    load_sft_training_readiness,
    validate_sft_training_readiness,
)
from about_llm.finetuning.reward_model import (
    LinearRewardTrainingReport,
    PairwiseRewardMetrics,
    fit_linear_pairwise_reward_model,
    pairwise_reward_metrics,
)
from about_llm.finetuning.target_dpo_control import (
    TARGET_DPO_CONTROL_VERSION,
    TARGET_DPO_EVIDENCE_BOUNDARY,
    TARGET_DPO_REPORT_VERSION,
    TargetDPOAdapterSpec,
    TargetDPOArtifactSpec,
    TargetDPOControlSpec,
    TargetDPOModelSpec,
    TargetDPOPairSpec,
    TargetDPORuntimeSpec,
    TargetDPOTrainerSpec,
    execute_loaded_target_dpo_control,
    load_target_dpo_control_spec,
    run_target_dpo_control,
    verify_recorded_target_dpo_report,
)
from about_llm.finetuning.target_lora_control import (
    TARGET_LORA_ARTIFACT_MANIFEST,
    TARGET_LORA_ARTIFACT_VERSION,
    TARGET_LORA_CONTROL_VERSION,
    TARGET_LORA_EVIDENCE_BOUNDARY,
    TARGET_LORA_REPORT_VERSION,
    TargetLoRAAdapterContract,
    TargetLoRAArtifactVerification,
    TargetLoRAControlSpec,
    TargetLoRAMessage,
    TargetLoRAModelContract,
    TargetLoRAOptimizerContract,
    TargetLoRATrainingResult,
    execute_loaded_target_lora_training,
    load_recorded_target_lora_report,
    load_target_lora_control_spec,
    run_target_lora_control,
    verify_recorded_target_lora_report,
    verify_target_lora_adapter_artifact,
)
from about_llm.finetuning.target_sft_label_control import (
    TARGET_SFT_LABEL_CONTROL_VERSION,
    TARGET_SFT_LABEL_EVIDENCE_BOUNDARY,
    TARGET_SFT_LABEL_REPORT_VERSION,
    TargetSFTArtifactSpec,
    TargetSFTLabelControlSpec,
    TargetSFTRuntimeSpec,
    TargetSFTSampleSpec,
    execute_loaded_target_sft_label_control,
    load_target_sft_label_control_spec,
    run_target_sft_label_control,
    verify_recorded_target_sft_label_report,
)
from about_llm.finetuning.template import (
    ASSISTANT_LABEL_AUDIT_VERSION,
    ASSISTANT_MASK_AUDIT_VERSION,
    AssistantLabelAuditReport,
    AssistantMaskAuditReport,
    AssistantMaskFeature,
    AssistantMaskPreparation,
    AssistantMaskSample,
    ChatTemplateRenderer,
    audit_assistant_label_projection,
    audit_assistant_masks,
    prepare_assistant_mask_features,
)

if TYPE_CHECKING:
    from about_llm.finetuning.amp_scaler import AMPGradScalerAnalysis
    from about_llm.finetuning.lora import LoRALinear


def __getattr__(name: str) -> Any:
    """Keep the torch-backed LoRA layer optional for data-only/core installs."""

    if name == "LoRALinear":
        from about_llm.finetuning.lora import LoRALinear

        return LoRALinear
    if name in {
        "AMP_GRAD_SCALER_CONTROL_VERSION",
        "AMP_GRAD_SCALER_EVIDENCE_BOUNDARY",
        "AMPGradScalerAnalysis",
        "run_cpu_amp_grad_scaler_control",
    }:
        from about_llm.finetuning import amp_scaler

        return getattr(amp_scaler, name)
    if name in {
        "TRAINING_RESUME_CHECKPOINT_VERSION",
        "TRAINING_RESUME_CONTROL_VERSION",
        "TRAINING_RESUME_EVIDENCE_BOUNDARY",
        "run_training_resume_process_control",
    }:
        from about_llm.finetuning import training_resume

        return getattr(training_resume, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

__all__ = [
    "AMP_GRAD_SCALER_CONTROL_VERSION",
    "AMP_GRAD_SCALER_EVIDENCE_BOUNDARY",
    "ASSISTANT_LABEL_AUDIT_VERSION",
    "ASSISTANT_MASK_AUDIT_VERSION",
    "MINHASH_LSH_VERSION",
    "PEFT_EXPORT_MANIFEST_FILENAME",
    "PEFT_EXPORT_MANIFEST_VERSION",
    "PREFERENCE_DATA_CONTRACT_VERSION",
    "PREFERENCE_EVALUATION_VERSION",
    "PREFERENCE_GOVERNANCE_AUDIT_VERSION",
    "PREFERENCE_JUDGMENT_AUDIT_VERSION",
    "PREFERENCE_JUDGMENT_CONTRACT_VERSION",
    "PREFERENCE_NEAR_DUPLICATE_AUDIT_VERSION",
    "PREFERENCE_SENSITIVE_CANDIDATE_DETECTOR_VERSION",
    "PREFERENCE_TOKENIZATION_AUDIT_VERSION",
    "PREFERENCE_TRAINING_READINESS_VERSION",
    "SFT_DATA_CONTRACT_VERSION",
    "SFT_GOVERNANCE_AUDIT_VERSION",
    "SFT_GOVERNANCE_POLICY_VERSION",
    "SFT_NEAR_DUPLICATE_AUDIT_VERSION",
    "SFT_SENSITIVE_CANDIDATE_DETECTOR_VERSION",
    "SFT_TRAINING_READINESS_VERSION",
    "TARGET_DPO_CONTROL_VERSION",
    "TARGET_DPO_EVIDENCE_BOUNDARY",
    "TARGET_DPO_REPORT_VERSION",
    "TARGET_LORA_ARTIFACT_MANIFEST",
    "TARGET_LORA_ARTIFACT_VERSION",
    "TARGET_LORA_CONTROL_VERSION",
    "TARGET_LORA_EVIDENCE_BOUNDARY",
    "TARGET_LORA_REPORT_VERSION",
    "TARGET_SFT_LABEL_CONTROL_VERSION",
    "TARGET_SFT_LABEL_EVIDENCE_BOUNDARY",
    "TARGET_SFT_LABEL_REPORT_VERSION",
    "TRAINING_RESUME_CHECKPOINT_VERSION",
    "TRAINING_RESUME_CONTROL_VERSION",
    "TRAINING_RESUME_EVIDENCE_BOUNDARY",
    "AMPGradScalerAnalysis",
    "AssistantLabelAuditReport",
    "AssistantMaskAuditReport",
    "AssistantMaskFeature",
    "AssistantMaskPreparation",
    "AssistantMaskSample",
    "CandidateDisposition",
    "CandidateException",
    "CategoricalMicrobatch",
    "CategoricalPolicyGradientReport",
    "CategoricalTokenRecord",
    "ChatMessage",
    "ChatTemplateRenderer",
    "DDPGradientAccumulationAnalysis",
    "DDPTokenMeanAnalysis",
    "DataSplit",
    "DuplicateGroup",
    "ExactLSHCandidateComparison",
    "FunctionToolCall",
    "FunctionToolDefinition",
    "GeneralizedAdvantageEstimate",
    "GovernanceOutcome",
    "GovernancePurpose",
    "GradientAccumulationAnalysis",
    "GroupRelativeAdvantageReport",
    "LinearRewardTrainingReport",
    "LoRALinear",
    "MessageRole",
    "MicrobatchGradientContribution",
    "MinHashLSHCandidatePair",
    "MinHashLSHCandidateReport",
    "MinHashLSHConfig",
    "MinHashLSHRecallAudit",
    "NearDuplicateFinding",
    "NearDuplicateProfile",
    "NearDuplicateView",
    "PEFTExportIdentity",
    "PEFTExportLimits",
    "PEFTExportVerification",
    "PPOClippedSurrogateReport",
    "PairwiseRewardMetrics",
    "PreferenceDataAuditReport",
    "PreferenceDuplicateGroup",
    "PreferenceEvaluationSummary",
    "PreferenceGovernanceAuditReport",
    "PreferenceJudgment",
    "PreferenceJudgmentAuditReport",
    "PreferenceLabel",
    "PreferenceNearDuplicateAuditReport",
    "PreferenceNearDuplicateFinding",
    "PreferenceNearDuplicateView",
    "PreferenceRecord",
    "PreferenceStrength",
    "PreferenceTemplateRenderer",
    "PreferenceTokenizationAuditReport",
    "PreferenceTokenizationSample",
    "PreferenceTrainingBindingReport",
    "PreferenceTrainingReadinessReport",
    "QLoRAMemoryEstimate",
    "SFTDataAuditReport",
    "SFTGovernanceAuditReport",
    "SFTGovernancePolicy",
    "SFTNearDuplicateAuditReport",
    "SFTRecord",
    "SFTTrainingBindingReport",
    "SFTTrainingReadinessReport",
    "SensitiveCandidateFinding",
    "SensitiveTextSurface",
    "SourceDecision",
    "SourceDecisionFinding",
    "SourceRule",
    "TargetDPOAdapterSpec",
    "TargetDPOArtifactSpec",
    "TargetDPOControlSpec",
    "TargetDPOModelSpec",
    "TargetDPOPairSpec",
    "TargetDPORuntimeSpec",
    "TargetDPOTrainerSpec",
    "TargetLoRAAdapterContract",
    "TargetLoRAArtifactVerification",
    "TargetLoRAControlSpec",
    "TargetLoRAMessage",
    "TargetLoRAModelContract",
    "TargetLoRAOptimizerContract",
    "TargetLoRATrainingResult",
    "TargetSFTArtifactSpec",
    "TargetSFTLabelControlSpec",
    "TargetSFTRuntimeSpec",
    "TargetSFTSampleSpec",
    "analyze_default_ddp_gradient_accumulation",
    "analyze_default_ddp_token_mean",
    "analyze_masked_token_gradient_accumulation",
    "audit_assistant_label_projection",
    "audit_assistant_masks",
    "audit_minhash_lsh_recall",
    "audit_preference_governance",
    "audit_preference_judgments",
    "audit_preference_near_duplicates",
    "audit_preference_records",
    "audit_preference_tokenization",
    "audit_sft_governance",
    "audit_sft_near_duplicates",
    "audit_sft_records",
    "bradley_terry_loss",
    "categorical_policy_gradient",
    "character_ngrams",
    "dpo_logit",
    "dpo_loss",
    "estimate_qlora_memory",
    "exact_recheck_lsh_candidates",
    "execute_loaded_target_dpo_control",
    "execute_loaded_target_lora_training",
    "execute_loaded_target_sft_label_control",
    "fit_linear_pairwise_reward_model",
    "generalized_advantage_estimation",
    "generate_minhash_lsh_candidates",
    "group_relative_advantages",
    "load_preference_judgments",
    "load_preference_records",
    "load_preference_training_readiness",
    "load_recorded_target_lora_report",
    "load_sft_governance_policy",
    "load_sft_records",
    "load_sft_training_readiness",
    "load_target_dpo_control_spec",
    "load_target_lora_control_spec",
    "load_target_sft_label_control_spec",
    "lsh_candidate_probability",
    "masked_mean",
    "minhash_signature",
    "normalize_near_duplicate_text",
    "oom_degradation_order",
    "pairwise_reward_metrics",
    "parse_utc_timestamp",
    "ppo_clipped_surrogate",
    "preference_audit_manifest_fingerprint",
    "prepare_assistant_mask_features",
    "run_cpu_amp_grad_scaler_control",
    "run_target_dpo_control",
    "run_target_lora_control",
    "run_target_sft_label_control",
    "run_training_resume_process_control",
    "scan_sensitive_text_surfaces",
    "sequence_log_probability",
    "shingle_jaccard",
    "summarize_preference_judgments",
    "validate_dpo_training_records",
    "validate_dpo_training_subset",
    "validate_preference_training_readiness",
    "validate_sft_training_readiness",
    "validate_training_records",
    "validate_training_subset",
    "variance_minimizing_score_baseline",
    "verify_peft_export_directory",
    "verify_recorded_target_dpo_report",
    "verify_recorded_target_lora_report",
    "verify_recorded_target_sft_label_report",
    "verify_target_lora_adapter_artifact",
    "write_peft_export_manifest_new",
]
