"""Inference measurement and sampling utilities."""

from about_llm.inference.beam_search import (
    BeamPrefix,
    BeamSearchResult,
    BeamSearchStep,
    BeamSequence,
    beam_search_from_probabilities,
)
from about_llm.inference.constrained import (
    ConstrainedDecodingResult,
    ConstrainedDecodingStep,
    ConstraintDeadEndError,
    LiteralSetConstraint,
    constrained_greedy_from_probabilities,
)
from about_llm.inference.continuous_batching import (
    BatchingRequest,
    ContinuousBatchingReport,
    ContinuousBatchStep,
    PrefillSlice,
    RequestSchedule,
    simulate_continuous_batching,
)
from about_llm.inference.kv_allocator import (
    KVAllocatorReport,
    KVAppendResult,
    KVBlockState,
    KVCapacityError,
    KVSequenceState,
    PagedKVAllocator,
)
from about_llm.inference.kv_preemption import (
    KVPreemptionBatchingReport,
    KVPreemptionBatchStep,
    KVPreemptionEvent,
    KVPreemptionRequestSchedule,
    KVWorkSlice,
    simulate_kv_preemption_batching,
)
from about_llm.inference.kv_quantization import (
    QuantizedKVCache,
    quantize_kv_cache_int8,
    quantized_kv_grouped_query_attention,
)
from about_llm.inference.memory import estimate_kv_cache_bytes
from about_llm.inference.metrics import (
    InferenceAttempt,
    InferenceMeasurement,
    InferenceSummary,
    RequestOutcome,
    WorkloadSLO,
    WorkloadSummary,
    classify_http_failure,
    summarize_attempts,
    summarize_measurements,
)
from about_llm.inference.minigpt_checkpoint import (
    MINIGPT_ARCHITECTURE_ID,
    MINIGPT_ARCHITECTURE_REVISION,
    MINIGPT_CHECKPOINT_FORMAT_VERSION,
    MINIGPT_CHECKPOINT_SCHEMA_VERSION,
    LoadedMiniGPTCheckpoint,
    MiniGPTCheckpointIdentity,
    MiniGPTCheckpointLimits,
    load_quantized_minigpt_checkpoint,
    read_quantized_minigpt_checkpoint,
    serialize_quantized_minigpt_checkpoint,
    write_quantized_minigpt_checkpoint_new,
)
from about_llm.inference.prefix_cache import (
    PrefixCache,
    PrefixCacheCapacityError,
    PrefixCacheEntryState,
    PrefixCacheIdentity,
    PrefixCacheLease,
    PrefixCacheLeaseError,
    PrefixCacheReport,
    sha256_prefix_fingerprint,
)
from about_llm.inference.quantization import (
    QUANTIZED_MATRIX_FORMAT_VERSION,
    GroupwiseQuantizedMatrix,
    PackedGroupwiseQuantizedMatrix,
    QuantizationError,
    quantization_error,
    quantize_symmetric_groupwise,
    quantized_linear,
)
from about_llm.inference.quantized_bundle import (
    QUANTIZED_BUNDLE_FORMAT_VERSION,
    QUANTIZED_BUNDLE_SCHEMA_VERSION,
    NamedQuantizedMatrix,
    QuantizedBundleIdentity,
    QuantizedBundleLimits,
    QuantizedMatrixBundle,
)
from about_llm.inference.roofline import RooflineBound, roofline_lower_bound
from about_llm.inference.sampling import (
    NextTokenSamplingStep,
    SamplingConfig,
    greedy_next_token,
    sample_next_token,
)
from about_llm.inference.speculative import (
    SpeculativeBlockResult,
    SpeculativeDistributionAudit,
    SpeculativeStepResult,
    audit_speculative_distribution,
    speculative_sample_step,
    verify_speculative_block,
)
from about_llm.inference.stop_matching import (
    IncrementalStopMatcher,
    StopMatcherReport,
    StopMatcherStateError,
    StopMatchUpdate,
)
from about_llm.inference.workload import (
    ArrivalProcess,
    ArrivalSchedule,
    build_arrival_schedule,
)

__all__ = [
    "MINIGPT_ARCHITECTURE_ID",
    "MINIGPT_ARCHITECTURE_REVISION",
    "MINIGPT_CHECKPOINT_FORMAT_VERSION",
    "MINIGPT_CHECKPOINT_SCHEMA_VERSION",
    "QUANTIZED_BUNDLE_FORMAT_VERSION",
    "QUANTIZED_BUNDLE_SCHEMA_VERSION",
    "QUANTIZED_MATRIX_FORMAT_VERSION",
    "ArrivalProcess",
    "ArrivalSchedule",
    "BatchingRequest",
    "BeamPrefix",
    "BeamSearchResult",
    "BeamSearchStep",
    "BeamSequence",
    "ConstrainedDecodingResult",
    "ConstrainedDecodingStep",
    "ConstraintDeadEndError",
    "ContinuousBatchStep",
    "ContinuousBatchingReport",
    "GroupwiseQuantizedMatrix",
    "IncrementalStopMatcher",
    "InferenceAttempt",
    "InferenceMeasurement",
    "InferenceSummary",
    "KVAllocatorReport",
    "KVAppendResult",
    "KVBlockState",
    "KVCapacityError",
    "KVPreemptionBatchStep",
    "KVPreemptionBatchingReport",
    "KVPreemptionEvent",
    "KVPreemptionRequestSchedule",
    "KVSequenceState",
    "KVWorkSlice",
    "LiteralSetConstraint",
    "LoadedMiniGPTCheckpoint",
    "MiniGPTCheckpointIdentity",
    "MiniGPTCheckpointLimits",
    "NamedQuantizedMatrix",
    "NextTokenSamplingStep",
    "PackedGroupwiseQuantizedMatrix",
    "PagedKVAllocator",
    "PrefillSlice",
    "PrefixCache",
    "PrefixCacheCapacityError",
    "PrefixCacheEntryState",
    "PrefixCacheIdentity",
    "PrefixCacheLease",
    "PrefixCacheLeaseError",
    "PrefixCacheReport",
    "QuantizationError",
    "QuantizedBundleIdentity",
    "QuantizedBundleLimits",
    "QuantizedKVCache",
    "QuantizedMatrixBundle",
    "RequestOutcome",
    "RequestSchedule",
    "RooflineBound",
    "SamplingConfig",
    "SpeculativeBlockResult",
    "SpeculativeDistributionAudit",
    "SpeculativeStepResult",
    "StopMatchUpdate",
    "StopMatcherReport",
    "StopMatcherStateError",
    "WorkloadSLO",
    "WorkloadSummary",
    "audit_speculative_distribution",
    "beam_search_from_probabilities",
    "build_arrival_schedule",
    "classify_http_failure",
    "constrained_greedy_from_probabilities",
    "estimate_kv_cache_bytes",
    "greedy_next_token",
    "load_quantized_minigpt_checkpoint",
    "quantization_error",
    "quantize_kv_cache_int8",
    "quantize_symmetric_groupwise",
    "quantized_kv_grouped_query_attention",
    "quantized_linear",
    "read_quantized_minigpt_checkpoint",
    "roofline_lower_bound",
    "sample_next_token",
    "serialize_quantized_minigpt_checkpoint",
    "sha256_prefix_fingerprint",
    "simulate_continuous_batching",
    "simulate_kv_preemption_batching",
    "speculative_sample_step",
    "summarize_attempts",
    "summarize_measurements",
    "verify_speculative_block",
    "write_quantized_minigpt_checkpoint_new",
]
