"""Framework-independent RAG building blocks."""

from about_llm.rag.answer_eval import (
    AnswerAction,
    ClaimVerdict,
    RecordedAnswer,
    RecordedClaim,
    evaluate_recorded_answers,
    load_recorded_answers,
)
from about_llm.rag.bm25 import BM25Index
from about_llm.rag.citations import (
    CitationAudit,
    CitationContext,
    audit_citations,
    build_citation_context,
)
from about_llm.rag.context_packing import (
    ContextCost,
    PackedCitationContext,
    PackingDecision,
    PackingReason,
    make_rag_chat_prompt_cost,
    pack_citation_context,
    utf8_byte_length,
)
from about_llm.rag.dense import DenseIndex, EmbeddingModel
from about_llm.rag.extractive import (
    EXACT_SPAN_JUDGMENT,
    EXTRACTIVE_ARTIFACT_VERSION,
    ExtractiveAnswerArtifact,
    ExtractiveAnswerConfig,
    ExtractiveSource,
    ExtractiveSpan,
    generate_extractive_answer,
)
from about_llm.rag.generation_policy import (
    DEFAULT_RAG_PUBLICATION_POLICY,
    RAG_PUBLICATION_POLICY_VERSION,
    RAG_PUBLICATION_REPLAY_EVIDENCE_BOUNDARY,
    RAG_PUBLICATION_REPLAY_REPORT_VERSION,
    PublicationAction,
    PublicationStage,
    RAGPublicationDecision,
    RAGPublicationPolicy,
    build_publication_policy_replay_report,
    evaluate_post_generation,
    evaluate_pre_generation,
    guard_rag_generation,
    verify_publication_policy_replay_report,
)
from about_llm.rag.guarded_transformers_control import (
    RAG_GUARDED_TRANSFORMERS_CONTROL_VERSION,
    RAG_GUARDED_TRANSFORMERS_EVIDENCE_BOUNDARY,
    RAG_GUARDED_TRANSFORMERS_REPORT_VERSION,
    execute_loaded_guarded_rag_transformers_control,
    load_guarded_rag_transformers_control_spec,
    run_guarded_rag_transformers_control,
    verify_recorded_guarded_rag_transformers_report,
)
from about_llm.rag.ingestion import (
    IngestionPlan,
    SourceChunk,
    SourceDocument,
    plan_incremental_update,
    split_markdown,
)
from about_llm.rag.models import Document, SearchResult
from about_llm.rag.rank_fusion import reciprocal_rank_fusion
from about_llm.rag.reranking import (
    RecordedRerankScore,
    RecordedRerankScorer,
    RerankCandidateTrace,
    RerankReport,
    RerankScorer,
    rerank_authorized_candidates,
)
from about_llm.rag.retriever_learning import (
    ContrastiveRetrievalReport,
    contrastive_retrieval_loss,
    late_interaction_scores,
    single_positive_info_nce,
    splade_max_pool,
)
from about_llm.rag.sqlite_backup import (
    SQLITE_BACKUP_MANIFEST_VERSION,
    SQLITE_LOGICAL_FINGERPRINT_REVISION,
    SQLiteChunkBackupManifest,
    create_sqlite_chunk_backup,
    load_sqlite_chunk_backup_manifest,
    restore_sqlite_chunk_backup,
    verify_sqlite_chunk_backup,
)
from about_llm.rag.sqlite_store import SQLiteChunkStore
from about_llm.rag.trace import (
    RAG_GENERATION_TRACE_AUDIT_VERSION,
    RAG_GENERATION_TRACE_VERSION,
    RAGGenerationTrace,
    RAGTraceAuditReport,
    RAGTraceCaseBinding,
    RAGTraceFinding,
    RAGTraceSource,
    audit_rag_generation_traces,
    load_rag_generation_traces,
)
from about_llm.rag.transformers_control import (
    RAG_TRANSFORMERS_CONTROL_VERSION,
    RAG_TRANSFORMERS_EVIDENCE_BOUNDARY,
    RAG_TRANSFORMERS_REPORT_VERSION,
    RAGControlCase,
    RAGControlDocument,
    RAGTransformersControlSpec,
    execute_loaded_rag_transformers_control,
    load_rag_transformers_control_spec,
    run_rag_transformers_control,
    validate_checkpoint_binding,
    verify_recorded_rag_transformers_report,
)

__all__ = [
    "DEFAULT_RAG_PUBLICATION_POLICY",
    "EXACT_SPAN_JUDGMENT",
    "EXTRACTIVE_ARTIFACT_VERSION",
    "RAG_GENERATION_TRACE_AUDIT_VERSION",
    "RAG_GENERATION_TRACE_VERSION",
    "RAG_GUARDED_TRANSFORMERS_CONTROL_VERSION",
    "RAG_GUARDED_TRANSFORMERS_EVIDENCE_BOUNDARY",
    "RAG_GUARDED_TRANSFORMERS_REPORT_VERSION",
    "RAG_PUBLICATION_POLICY_VERSION",
    "RAG_PUBLICATION_REPLAY_EVIDENCE_BOUNDARY",
    "RAG_PUBLICATION_REPLAY_REPORT_VERSION",
    "RAG_TRANSFORMERS_CONTROL_VERSION",
    "RAG_TRANSFORMERS_EVIDENCE_BOUNDARY",
    "RAG_TRANSFORMERS_REPORT_VERSION",
    "SQLITE_BACKUP_MANIFEST_VERSION",
    "SQLITE_LOGICAL_FINGERPRINT_REVISION",
    "AnswerAction",
    "BM25Index",
    "CitationAudit",
    "CitationContext",
    "ClaimVerdict",
    "ContextCost",
    "ContrastiveRetrievalReport",
    "DenseIndex",
    "Document",
    "EmbeddingModel",
    "ExtractiveAnswerArtifact",
    "ExtractiveAnswerConfig",
    "ExtractiveSource",
    "ExtractiveSpan",
    "IngestionPlan",
    "PackedCitationContext",
    "PackingDecision",
    "PackingReason",
    "PublicationAction",
    "PublicationStage",
    "RAGControlCase",
    "RAGControlDocument",
    "RAGGenerationTrace",
    "RAGPublicationDecision",
    "RAGPublicationPolicy",
    "RAGTraceAuditReport",
    "RAGTraceCaseBinding",
    "RAGTraceFinding",
    "RAGTraceSource",
    "RAGTransformersControlSpec",
    "RecordedAnswer",
    "RecordedClaim",
    "RecordedRerankScore",
    "RecordedRerankScorer",
    "RerankCandidateTrace",
    "RerankReport",
    "RerankScorer",
    "SQLiteChunkBackupManifest",
    "SQLiteChunkStore",
    "SearchResult",
    "SourceChunk",
    "SourceDocument",
    "audit_citations",
    "audit_rag_generation_traces",
    "build_citation_context",
    "build_publication_policy_replay_report",
    "contrastive_retrieval_loss",
    "create_sqlite_chunk_backup",
    "evaluate_post_generation",
    "evaluate_pre_generation",
    "evaluate_recorded_answers",
    "execute_loaded_guarded_rag_transformers_control",
    "execute_loaded_rag_transformers_control",
    "generate_extractive_answer",
    "guard_rag_generation",
    "late_interaction_scores",
    "load_guarded_rag_transformers_control_spec",
    "load_rag_generation_traces",
    "load_rag_transformers_control_spec",
    "load_recorded_answers",
    "load_sqlite_chunk_backup_manifest",
    "make_rag_chat_prompt_cost",
    "pack_citation_context",
    "plan_incremental_update",
    "reciprocal_rank_fusion",
    "rerank_authorized_candidates",
    "restore_sqlite_chunk_backup",
    "run_guarded_rag_transformers_control",
    "run_rag_transformers_control",
    "single_positive_info_nce",
    "splade_max_pool",
    "split_markdown",
    "utf8_byte_length",
    "validate_checkpoint_binding",
    "verify_publication_policy_replay_report",
    "verify_recorded_guarded_rag_transformers_report",
    "verify_recorded_rag_transformers_report",
    "verify_sqlite_chunk_backup",
]
